---
apiVersion: v1 
kind: ReplicationController 
metadata: 
  name: php-apache 
spec: 
  replicas: 1 
  template: 
    metadata: 
      name: php-apache 
      labels: 
        app: php-apache 
    spec: 
      containers: 
      - name: php-apache 
        image: kubeguide/guestbook-php-frontend
        resources: 
          requests: 
            cpu: 200m 
        ports: 
        - containerPort: 80
